# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2023-12-04 17:57:05
"""
import arcpy
from sys import argv

def PlotUTM(Coordinates_Data, Coordinate_System, Points_Output, X_Field="Easting", Y_Field="Northing"):  # Plot UTM

    # Set Geoprocessing environments
    arcpy.env.extent = "DEFAULT"
    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = True
    
    Z_Field = ""

    # arcpy.ImportToolbox(r"c:\esri\arcgispro\pro\Resources\ArcToolbox\toolboxes\Data Management Tools.tbx")

    # Process: XY Table To Point (XY Table To Point) (management)
    arcpy.management.XYTableToPoint(Coordinates_Data, Points_Output, X_Field, Y_Field, Z_Field, Coordinate_System)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Temp\TestArcPy\Output", workspace=r"C:\Temp\TestArcPy\Output"):
        PlotUTM(*argv[1:])
